Error messages go to stderr.

diff --git a/ansible/ora_set_archivelog_mode.sh.j2 b/ansible/ora_set_archivelog_mode.sh.j2
--- a/ansible/ora_set_archivelog_mode.sh.j2
+++ b/ansible/ora_set_archivelog_mode.sh.j2
@@ -43,7 +43,7 @@ for line in ${EXPECTED_OUTPUT}; do
         tail -n +$n t.out > t0.out
         mv t0.out t.out
     else
-        echo "Looks like an error, we didn't find '$line' in '$FN'" 1>&1
+        echo "Looks like an error, we didn't find '$line' in '$FN'" 1>&2
         exit 1
     fi
 done
